#!/bin/bash
#
# list of possible environment variables
#   - OPCUASTACK_VERSION_MAJOR
#   - OPCUASTACK_VERSION_MINOR
#   - OPCUASTACK_VERSION_PATCH
#

OPCUASTACK_VERSION_MAJOR_=${OPCUASTACK_VERSION_MAJOR:-1}
OPCUASTACK_VERSION_MINOR_=${OPCUASTACK_VERSION_MINOR:-0}
OPCUASTACK_VERSION_PATCH_=${OPCUASTACK_VERSION_PATCH:-0}

VERSION_OPCUASTACK=${OPCUASTACK_VERSION_MAJOR_}.${OPCUASTACK_VERSION_MINOR_}.${OPCUASTACK_VERSION_PATCH_}

